version: '3.9'

volumes:
  mongo-data:
  mysql-data:

# networks:
#   myNetworkMicroservice:
    # driver: bridge
    # external: true

services:
  app:
    container_name: javaMicroservice
    tty: true 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    ports:
      # - "127.0.0.1:8080:8080"
      - "8080:8080"
    command: sleep infinity 
    network_mode: "host"
    # networks:
    #   - myNetworkMicroservice
    depends_on:
      - db
      - mysql
    # links:
    #   - db
    #   - mysql
  db:
    container_name: productmongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      # - '127.0.0.1:27017:27017'
      - "27017:27017"
    # networks:
    #   - myNetworkMicroservice
    network_mode: "host"
  mysql:
    container_name: ordermysql
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    # networks:
    #   - myNetworkMicroservice
    network_mode: "host"